// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SerializationConfigurationTypes.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package [VISUAL_STUDIO_TEMPLATE_PACKAGE_ID] ([VISUAL_STUDIO_TEMPLATE_PACKAGE_VERSION])
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace [PROJECT_NAME]
{
    using System;
    using System.CodeDom.Compiler;
    using System.Diagnostics.CodeAnalysis;

    using [ORGANIZATION].[SUBSYSTEM_NAME].Serialization.Bson;
    using [ORGANIZATION].[SUBSYSTEM_NAME].Serialization.Json;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("[VISUAL_STUDIO_TEMPLATE_PACKAGE_ID]", "[VISUAL_STUDIO_TEMPLATE_PACKAGE_VERSION]")]
    public static class SerializationConfigurationTypes
    {
        public static Type BsonConfigurationType => typeof([SUBSYSTEM_NAME]BsonSerializationConfiguration);

        public static Type JsonConfigurationType => typeof([SUBSYSTEM_NAME]JsonSerializationConfiguration);
    }
}